"""add batch processing models

Revision ID: 240f6dc265cb
Revises: 50fbea6f35e8
Create Date: 2025-12-28 02:50:40.608018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240f6dc265cb'
down_revision = '50fbea6f35e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
